version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 277707106820.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t patel-flask-app .
      - docker tag patel-flask-app:latest 277707106820.dkr.ecr.ca-central-1.amazonaws.com/patel-ecr:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 277707106820.dkr.ecr.ca-central-1.amazonaws.com/patel-ecr:latest
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"patel-container","imageUri":"277707106820.dkr.ecr.ca-central-1.amazonaws.com/patel-ecr:latest"}]' > imagedefinitions.json
      - echo Build completed on `date` # Updated for new commit
artifacts:
  files:
    - imagedefinitions.json
